import fs from 'node:fs';
import fsp from 'node:fs/promises';
import {isErrnoException} from './utils/errors.js';
import * as validate from './utils/validate.js';

/** Specifies the format in which file contents are returned. */
type ReturnAs = 'utf8' | 'buffer' | 'json' | 'jsonWithDates';

const supportedReturnAs: ReturnAs[] = [
  'utf8',
  'buffer',
  'json',
  'jsonWithDates',
];

/** Validates arguments for the read method, ensuring `returnAs` is a supported value. */
const validateInput = (
  methodName: string,
  path: string,
  returnAs?: string,
): void => {
  const methodSignature = `${methodName}(path, returnAs)`;
  validate.argument(methodSignature, 'path', path, ['string']);
  validate.argument(methodSignature, 'returnAs', returnAs, [
    'string',
    'undefined',
  ]);

  if (returnAs && !(supportedReturnAs as string[]).includes(returnAs)) {
    throw new Error(
      `Argument "returnAs" passed to ${methodSignature} must have one of values: ${supportedReturnAs.join(
        ', ',
      )}`,
    );
  }
};

// Matches strings generated by Date.toJSON()
// which is called to serialize date to JSON.
/** JSON reviver that converts ISO 8601 date strings back into Date objects. */
const jsonDateParser = (_key: string, value: unknown): unknown => {
  const reISO =
    /^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2}\.\d*)(?:Z|(\+|-)([\d|:]*))?$/;
  if (typeof value === 'string' && reISO.test(value)) {
    return new Date(value);
  }

  return value;
};

type NicerJsonError = {
  originalError: Error;
} & Error;

/** Wraps a JSON parse error with the file path for easier debugging. */
const makeNicerJsonParsingError = (
  path: string,
  error: Error,
): NicerJsonError => {
  const nicerError = new Error(
    `JSON parsing failed while reading ${path} [${error}]`,
  ) as NicerJsonError;
  nicerError.originalError = error;
  return nicerError;
};

// ---------------------------------------------------------
// SYNC
// ---------------------------------------------------------

/** Reads a file synchronously in the specified format. Returns `undefined` if the file doesn't exist. */
const readSync = (
  path: string,
  returnAs?: ReturnAs,
): string | Buffer | unknown | undefined => {
  const returnValueAs: ReturnAs = returnAs || 'utf8';
  let data: string | Buffer;

  try {
    data =
      returnValueAs === 'buffer'
        ? fs.readFileSync(path)
        : fs.readFileSync(path, {encoding: 'utf8'});
  } catch (error: unknown) {
    if (isErrnoException(error) && error.code === 'ENOENT') {
      // If file doesn't exist return undefined instead of throwing.
      return undefined;
    }

    // Otherwise rethrow the error
    throw error;
  }

  try {
    if (returnValueAs === 'json') {
      return JSON.parse(data as string);
    }

    if (returnValueAs === 'jsonWithDates') {
      return JSON.parse(data as string, jsonDateParser);
    }
  } catch (error) {
    throw makeNicerJsonParsingError(path, error as Error);
  }

  return data;
};

// ---------------------------------------------------------
// ASYNC
// ---------------------------------------------------------

/** Reads a file asynchronously in the specified format. Returns `undefined` if the file doesn't exist. */
const readAsync = async (
  path: string,
  returnAs?: ReturnAs,
): Promise<string | Buffer | unknown | undefined> => {
  const returnValueAs: ReturnAs = returnAs || 'utf8';
  let data: string | Buffer;

  try {
    data = await (returnValueAs === 'buffer'
      ? fsp.readFile(path)
      : fsp.readFile(path, {encoding: 'utf8'}));
  } catch (error: unknown) {
    if (isErrnoException(error) && error.code === 'ENOENT') {
      // If file doesn't exist return undefined instead of throwing.
      return undefined;
    }

    // Otherwise throw
    throw error;
  }

  // Make final parsing of the data before returning.
  try {
    if (returnValueAs === 'json') {
      return JSON.parse(data as string);
    }

    if (returnValueAs === 'jsonWithDates') {
      return JSON.parse(data as string, jsonDateParser);
    }
  } catch (error) {
    throw makeNicerJsonParsingError(path, error as Error);
  }

  return data;
};

// ---------------------------------------------------------
// API
// ---------------------------------------------------------

export {validateInput, readSync as sync, readAsync as async};
